name: Build macOS ISO

on:
  workflow_dispatch:

jobs:
  build-macos-iso:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download macOS Installer
      run: |
        curl -L "https://swcdn.apple.com/content/downloads/10/18/047-32248-A_Y7S9K47C9M/rqg3zuwb6dkofsdilmz22awvxtq2sxwr15/InstallAssistant.pkg" -o InstallAssistant.pkg

    - name: Install macOS Installer
      run: |
        sudo installer -pkg InstallAssistant.pkg -target /

    - name: Create ISO
      run: |
        hdiutil create -o macos_tmp -size 16000m -layout SPUD -fs HFS+J
        hdiutil attach macos_tmp.dmg -mountpoint /Volumes/install_build
        sudo /Applications/Install\ macOS\ Big\ Sur.app/Contents/Resources/createinstallmedia \
          --volume /Volumes/install_build --nointeraction
        hdiutil detach "/Volumes/Install macOS Big Sur"
        hdiutil convert macos_tmp.dmg -format UDTO -o macos
        mv macos.cdr macOS-BigSur.iso

    - name: Upload ISO
      uses: actions/upload-artifact@v4
      with:
        name: macOS-BigSur
        path: macOS-BigSur.iso